### PR TITLE
add python packages coverage,matplotlib, pyminuit2

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by hegner** [comment]
@gartung - but those exist upstream already?!

**Comment by gartung** [comment]
I did not see them. I wanted to push this to avoid duplication of effort.

**Comment by hegner** [comment]
They all start with `py-`

**Comment by gartung** [comment]
Doh... looking at features-merged branch which is outdated...

**Comment by hegner** [comment]
no. those are weeks old...

**Comment by hegner** [comment]
@gartung- but feel free to merge upstream. doesn't harm from time to time

**Pull request merged**
